services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rivaya-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rivaya
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - rivaya-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rivaya -q"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: rivaya-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rivaya-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Service
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: rivaya-api
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api:/app/apps/api # Mount the API source code for hot-reloading
      # Remove the /app/node_modules volume mount. Let Docker build and manage node_modules internally.
      # If you need to share node_modules from the host for specific reasons, consider mounting the entire monorepo root:
      # - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rivaya-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web Application
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: rivaya-web
    restart: unless-stopped
    env_file:
      - ./apps/web/.env.local
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app/apps/web
      - /app/node_modules
      - /app/.next
    depends_on:
      api:
        condition: service_healthy
    networks:
      - rivaya-network

  # Mobile Development Server
  mobile:
    build:
      context: .
      dockerfile: apps/mobile/Dockerfile
    container_name: rivaya-mobile
    restart: unless-stopped
    env_file:
      - ./apps/mobile/.env
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./apps/mobile:/app/apps/mobile
      - /app/node_modules
    depends_on:
      api:
        condition: service_healthy
    networks:
      - rivaya-network

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: rivaya-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - web
    networks:
      - rivaya-network
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  rivaya-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
