version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rivaya_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rivaya_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Supabase Local Development
  supabase:
    image: supabase/postgres:15.1.0.117
    container_name: rivaya_supabase
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      POSTGRES_HOST: supabase
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "54322:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data
      - ./supabase:/supabase
    networks:
      - rivaya_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Web Application
  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: runner
    container_name: rivaya_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@supabase:5432/postgres
      - SUPABASE_URL=http://supabase:54321
      - SUPABASE_ANON_KEY=your-anon-key
      - REDIS_URL=redis://redis:6379
      - NEXT_PUBLIC_API_URL=http://api:3001
    depends_on:
      supabase:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started
    networks:
      - rivaya_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # NestJS API Application
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: runner
    container_name: rivaya_api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@supabase:5432/postgres
      - SUPABASE_URL=http://supabase:54321
      - SUPABASE_ANON_KEY=your-anon-key
      - REDIS_URL=redis://redis:6379
      - PORT=3001
      - JWT_SECRET=your-super-secret-jwt-token-with-at-least-32-characters-long
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key
      - STRIPE_WEBHOOK_SECRET=whsec_your_stripe_webhook_secret
    depends_on:
      supabase:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rivaya_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Expo Mobile Development Server
  mobile:
    build:
      context: .
      dockerfile: mobile/Dockerfile
      target: dev
    container_name: rivaya_mobile
    restart: unless-stopped
    ports:
      - "8081:8081"   # Metro bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # Expo DevTools
      - "19002:19002" # Expo DevTools
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - EXPO_TUNNEL=true
      - EXPO_PUBLIC_API_URL=http://api:3001
    depends_on:
      api:
        condition: service_started
    networks:
      - rivaya_network
    volumes:
      - ./mobile:/app/mobile
      - /app/mobile/node_modules

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: rivaya_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - rivaya_network

volumes:
  redis_data:
    driver: local
  supabase_data:
    driver: local

networks:
  rivaya_network:
    driver: bridge
