version: 2.1
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0

workflows:
  build-test-deploy:
    jobs:
      - test-web
      - test-api
      - test-mobile
      - build-images:
          requires: [test-web, test-api, test-mobile]

jobs:
  test-web:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm --filter @rivaya/web run lint
      - run: pnpm --filter @rivaya/web run test
      - run: pnpm --filter @rivaya/web run build
  
  test-api:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm --filter @rivaya/api run lint
      - run: pnpm --filter @rivaya/api run test
      - run: pnpm --filter @rivaya/api run build
  
  test-mobile:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm --filter @rivaya/mobile run lint
      - run: pnpm --filter @rivaya/mobile run test
  
  build-images:
    machine: true
    steps:
      - checkout
      - docker/build:
          image: rivaya/web
          dockerfile: apps/web/Dockerfile
          tag: latest,$CIRCLE_SHA1
      - docker/build:
          image: rivaya/api
          dockerfile: apps/api/Dockerfile
          tag: latest,$CIRCLE_SHA1
